OUTPUT_DIR: ''
TMP_DIR: ''

# General options
CRS: 'EPSG:2056'
YEAR_START: 2013
YEAR_END: 2022

# CID (cells IDs) raster path
CID_PATH: '..\files\cids.tif'

# Contract and damage data directories
DIR_CONTRACTS: ''
DIR_CLAIMS: ''

# Path to the events parquet file
EVENTS_PATH: ''

# DEMs (with different resolutions)
DEM_PATHS:
  - ''
  - ''
  - ''
  - ''

# Computation of the flow accumulation
LAKES_PATH: ''
FLOWACC_RIVER_THRESHOLD: 50000
