OUTPUT_DIR: ''

# Synthetic csv files v2019
CSV_2019_TRIGGER: ''
CSV_2019_ALL: ''

# DEMs (with different resolutions)
DEM_PATHS:
  - ''
  - ''
  - ''
  - ''

# Computation of the flow accumulation
LAKES_PATH: ''
FLOWACC_RIVER_THRESHOLD: 50000
